fusion:  
  solr:
    nodePools:
      - name: ""
        resources:
          limits:
            memory: 12Gi
            cpu: 1500m
          requests:
            memory: 5Gi
            cpu: 500m
      - name: "analytics"
        javaMem: "-Xms9g -Xmx9g"
        replicaCount: 3
        storageSize: "50Gi"
        logLevel: WARN
        nodeSelector:
          fusion_node_type: [[.Env]]-analytics
        resources:
          limits:
            memory: 22Gi
            cpu: 4
          requests:
            memory: 20Gi
            cpu: 3
      - name: "search"
        javaMem: "-Xms10g -Xmx10g"
        replicaCount: 3
        storageSize: "50Gi"
        logLevel: WARN
        nodeSelector:
          fusion_node_type: [[.Env]]-search
        resources:
          limits:
            memory: 22Gi
            cpu: 6
          requests:
            memory: 20Gi
            cpu: 6
    nodeSelector:
      fusion_node_type: [[.Env]]-system
    updateStrategy:
      type: "RollingUpdate"
    javaMem: "-Xms5g -Xmx5g -Dfusion_node_type=[[.Env]]-system"
    solrGcTune: "-XX:-OmitStackTraceInFastThrow -XX:+UseG1GC -XX:+UseStringDeduplication -XX:+PerfDisableSharedMem -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=250 -XX:+UseLargePages -XX:+AlwaysPreTouch"
    solrOpts: "-Dsolr.disableConfigSetsCreateAuthChecks=true -Dlog4j2.formatMsgNoLookups=true"
    volumeClaimTemplates:
      [[if or (eq .CloudProvider "azure") (eq .CloudProvider "gcp") -]]
      storageClassName: "managed-premium"
      [[- end]]
      storageSize: "100Gi"
    replicaCount: 3
    podAnnotations:
      fluentd.active: "true"
    livenessProbe:
      initialDelaySeconds: 30
      periodSeconds: 15
      timeoutSeconds: 5
      failureThreshold: 20
    readinessProbe:
      initialDelaySeconds: 30
      periodSeconds: 15
      timeoutSeconds: 5
      failureThreshold: 20
    exporter:
      livenessProbe:
        initialDelaySeconds: 30
        failureThreshold: 20
      readinessProbe:
        initialDelaySeconds: 30
        failureThreshold: 20
      enabled: true
      threads: 10
      javaMem: -Xmx3g
      resources:
        limits:
          cpu: "3"
          memory: 4Gi
        requests:
          cpu: 500m
          memory: 700Mi
      podAnnotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9983"
        prometheus.io/path: "/metrics"
      nodeSelector:
        fusion_node_type: infra
      javaOpts: "-Dlog4j2.formatMsgNoLookups=true"
  fusion-indexing:
    replicaCount: 2
    nodeSelector:
      fusion_node_type: [[.Env]]-analytics
    readinessProbe:
      initialDelaySeconds: 90
    javaToolOptions: "-Xms2g -Xmx4g -Dserver.jetty.max-threads=1000 -Dcom.lucidworks.httpclient.defaultMaxPerRoute=1000 -Dcom.lucidworks.httpclient.maxTotalConnections=1000 -Dhttp.maxConnections=1000 -Dmanagement.health.kubernetes.enabled=false -Dspring.cloud.kubernetes.discovery.catalogServicesWatchDelay=15000 -Dribbon.ServerListRefreshInterval=15000"
    pod:
      annotations:
        prometheus.io/port: "8765"
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        fluentd.active: "true"
