fusion:  
  solr:
    nodePools:
      - name: ""
      - name: "analytics"
        javaMem: "-Xms2g -Xmx2g"
        replicaCount: 1
        storageSize: "50Gi"
        logLevel: WARN
        nodeSelector:
          fusion_node_type: [[.Env]]
        resources:
          requests:
            cpu: 500m
            memory: 5Gi
          limits:
            cpu: 1
            memory: 5Gi
      - name: "search"
        javaMem: "-Xms2g -Xmx2g"
        replicaCount: 1
        storageSize: "50Gi"
        logLevel: WARN
        nodeSelector:
          fusion_node_type: [[.Env]]
        resources:
          requests:
            cpu: 500m
            memory: 5Gi
          limits:
            cpu: 1
            memory: 5Gi
    nodeSelector:
      fusion_node_type: [[.Env]]
    updateStrategy:
      type: "RollingUpdate"
    javaMem: "-Xms5g -Xmx5g -Dfusion_node_type=system"
    solrGcTune: "-XX:-OmitStackTraceInFastThrow -XX:+UseG1GC -XX:+UseStringDeduplication -XX:+PerfDisableSharedMem -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=250 -XX:+UseLargePages -XX:+AlwaysPreTouch"
    solrOpts: "-Dsolr.disableConfigSetsCreateAuthChecks=true -Dlog4j2.formatMsgNoLookups=true"
    volumeClaimTemplates:
      [[if (eq .CloudProvider "azure") -]]
      storageClassName: "managed-premium"
      [[- end]]
      storageSize: "100Gi"
    replicaCount: 1
    podAnnotations:
      fluentd.active: "true"
    livenessProbe:
      initialDelaySeconds: 30
      periodSeconds: 15
      timeoutSeconds: 5
      failureThreshold: 20
    readinessProbe:
      initialDelaySeconds: 30
      periodSeconds: 15
      timeoutSeconds: 5
      failureThreshold: 20
    exporter:
      livenessProbe:
        initialDelaySeconds: 30
        failureThreshold: 20
      readinessProbe:
        initialDelaySeconds: 30
        failureThreshold: 20
      enabled: true
      threads: 10
      javaMem: -Xmx4g
      resources:
        limits:
          cpu: "3"
          memory: 4Gi
        requests:
          cpu: 500m
          memory: 700Mi
      podAnnotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9983"
        prometheus.io/path: "/metrics"
      nodeSelector:
        fusion_node_type: infra
      javaOpts: "-Dlog4j2.formatMsgNoLookups=true"
  fusion-indexing:
    resources:
      requests:
        cpu: "500m"
        memory: "800Mi"
      limits:
        cpu: "900m"
        memory: "1600Mi"
    replicaCount: 1
    nodeSelector:
      fusion_node_type: [[.Env]]
    readinessProbe:
      initialDelaySeconds: 90
    javaToolOptions: "-Dserver.jetty.max-threads=1000 -Dcom.lucidworks.httpclient.defaultMaxPerRoute=1000 -Dcom.lucidworks.httpclient.maxTotalConnections=1000 -Dhttp.maxConnections=1000 -Dmanagement.health.kubernetes.enabled=false -Dspring.cloud.kubernetes.discovery.catalogServicesWatchDelay=15000 -Dribbon.ServerListRefreshInterval=15000"
    pod:
      annotations:
        prometheus.io/port: "8765"
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        fluentd.active: "true"