fusion:
  solr:
    nodePools:
      - name: ""
        javaMem: "-Xms3g -Xmx3g"
        replicaCount: 1
        logLevel: WARN
      - name: "search"
        javaMem: "-Xms3g -Xmx3g"
        replicaCount: 1
        storageSize: "50Gi"
        logLevel: WARN
        nodeSelector:
          fusion_node_type: [[.Env]]-search
        resources:
          limits:
            memory: 5Gi
            cpu: 2
          requests:
            memory: 2Gi
            cpu: 1
    nodeSelector:
      fusion_node_type: [[.Env]]-system
    resources:
      limits:
        memory: 5Gi
        cpu: 2
      requests:
        memory: 2Gi
        cpu: 1
    updateStrategy:
      type: "RollingUpdate"
    javaMem: "-Xms3g -Xmx3g -Dfusion_node_type=[[.Env]]-system"
    solrGcTune: "-XX:-OmitStackTraceInFastThrow -XX:+UseG1GC -XX:+UseStringDeduplication -XX:+PerfDisableSharedMem -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=250 -XX:+UseLargePages -XX:+AlwaysPreTouch"
    solrOpts: "-Dlog4j2.formatMsgNoLookups=true"
    volumeClaimTemplates:
      storageClassName: "managed-premium"
      storageSize: "100Gi"
    replicaCount: 1
    podAnnotations:
      fluentd.active: "true"
    livenessProbe:
      initialDelaySeconds: 30
      periodSeconds: 15
      timeoutSeconds: 5
      failureThreshold: 20
    readinessProbe:
      initialDelaySeconds: 30
      periodSeconds: 15
      timeoutSeconds: 5
      failureThreshold: 20
    exporter:
      livenessProbe:
        initialDelaySeconds: 30
        failureThreshold: 20
      readinessProbe:
        initialDelaySeconds: 30
        failureThreshold: 20
      enabled: true
      threads: 10
      javaMem: -Xmx3g
      resources:
        limits:
          cpu: 671m
          memory: 3877Mi
        requests:
          cpu: 223m
          memory: 3877Mi
      podAnnotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9983"
        prometheus.io/path: "/metrics"
      nodeSelector:
        fusion_node_type: infra
      javaOpts: "-Dlog4j2.formatMsgNoLookups=true"
  fusion-indexing:
    replicaCount: 2
    nodeSelector:
      fusion_node_type: [[.Env]]-analytics
    readinessProbe:
      initialDelaySeconds: 90
    javaToolOptions: "-Xms1g -Xmx1g -Dserver.jetty.max-threads=1000 -Dcom.lucidworks.httpclient.defaultMaxPerRoute=1000 -Dcom.lucidworks.httpclient.maxTotalConnections=1000 -Dhttp.maxConnections=1000 -Dmanagement.health.kubernetes.enabled=false -Dspring.cloud.kubernetes.discovery.catalogServicesWatchDelay=15000 -Dribbon.ServerListRefreshInterval=15000"
    pod:
      annotations:
        prometheus.io/port: "8765"
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        fluentd.active: "true"
