fusion:  
  admin-ui:
    resources:
      limits:
        cpu: 25m
        memory: 250Mi
      requests:
        cpu: 25m
        memory: 250Mi

  zookeeper:
    resources:
      requests:
        memory: 1500Mi
        cpu: 200m
      limits:
        memory: 2Gi
        cpu: 800m

  fusion-indexing:
    resources:
      limits:
        cpu: 1
        memory: 2990Mi
      requests:
        cpu: 92m
        memory: 1401Mi

  query-pipeline:
    resources:
      limits:
        cpu: "1800m"
        memory: "5Gi"
      requests:
        cpu: "1200m"
        memory: "5Gi"

  #api-gateway:
  #  resources:
  #    limits:
  #      cpu: "3500m"
  #      memory: "8Gi"
  #    requests:
  #      cpu: "3"
  #      memory: "4Gi"

  auth-ui:
    resources:
      limits:
        cpu: 25m
        memory: 250Mi
      requests:
        cpu: 25m
        memory: 250Mi

  classic-rest-service:
    javaToolOptions: -Xms3g -Xmx5g -Xss256k -Dhttp.maxConnections=1000
    resources:
      requests:
        cpu: "600m"
        memory: "3Gi"
      limits:
        cpu: "1200m"
        memory: "5Gi"

  devops-ui:
    resources:
      limits:
        cpu: 25m
        memory: 250Mi
      requests:
        cpu: 25m
        memory: 250Mi

  fusion-admin:
    #jvmOptions: "-Xms1g -Xmx2g -Xss256k -Dhttp.maxConnections=1000 -XX:PermSize=256m -XX:MaxPermSize=512m"
    resources:
      limits:
        cpu: 1
        memory: 1657Mi
      requests:
        cpu: 34m
        memory: 1245Mi

  insights:
    resources:
      limits:
        cpu: 25m
        memory: 391Mi
      requests:
        cpu: 25m
        memory: 308Mi

  job-launcher:
    javaToolOptions: "-Xmx3g"

  job-rest-server:
    #javaToolOptions: "-Xmx1024m -Xms256m"

  ml-model-service:
    #javaToolOptions: ""
    pythonService:
      resources:
        requests:
          memory: 1Gi
          cpu: 500m
        limits:
          memory: 3Gi
          cpu: 1
    javaService:
      resources:
        requests:
          memory: 2Gi
          cpu: 500m
        limits:
          memory: 3Gi
          cpu: 1

  connectors:
    #javaOpts: "-Xms1g -Xmx2g -Xss256k -Dhttp.maxConnections=1000"
    resources:
      limits:
        cpu: "200m"
        memory: 2Gi
      requests:
        cpu: "100m"
        memory: 1Gi

  connectors-backend:
    #javaOpts: "-Xms1g -Xmx2g -Xss256k -Dhttp.maxConnections=1000"
    resources:
      limits:
        cpu: 323m
        memory: 932Mi
      requests:
        cpu: 270m
        memory: 932Mi

  rules-ui:
    resources:
      limits:
        cpu: 25m
        memory: 250Mi
      requests:
        cpu: 25m
        memory: 250Mi

  # NOTE: Apply the Solr resource requests / limits in the solr: section of your main custom values yaml

  sql-service:
    #jvmOptions: "-XX:+UseG1GC -XX:+PrintGC -Xloggc:/work/sql-gc-%t.log -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=5 -XX:GCLogFileSize=2M -Xms4g -Xmx4g"
    resources:
      limits:
        cpu: "1"
        memory: 5Gi
      requests:
        cpu: "200m"
        memory: 2Gi

  webapps:
    #javaToolOptions: ""
    resources:
      limits:
        cpu: "2"
        memory: 2Gi
      requests:
        cpu: "500m"
        memory: "400Mi"