fusion:
  api-gateway:
    ingress:
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/proxy-body-size: 10m
        nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
      enabled: true
      [[if HasPrefix .ClusterType "non-prod" -]]
      host: "[[.CustomerName]]-[[.Namespace]].[[.Domain]]"
      [[- else -]]
      host: "[[.CustomerName]].[[.Domain]]"
      [[- end]]
      path: "/"
      tls:
        enabled: true