cluster_name: "lw-testcustomer-non-prod"
cluster_type: "non-prod"
region: "us-west1"
project_id: "managed-fusion"
repo_name: "testcustomer-config"
argocd_host: "testcustomer-non-prod-argocd.b.lucidworks.cloud"
argocd_host_tls_name: "testcustomer-non-prod-argocd-b-lucidworks-cloud"