groups:
  - name: pvc.disk
    rules:
      - alert: LowDisk
        expr: ((1 - (kubelet_volume_stats_available_bytes / kubelet_volume_stats_capacity_bytes)) * 100) > 90
        for: 1m
        labels:
          severity: s1
          env: '{{ $labels.namespace }}'
          customer: '[[.CustomerName]]'
          cluster: '[[.ClusterName]]'
          object: '{{ $labels.persistentvolumeclaim }}'
        annotations:
          description: 'Customer: [[.CustomerName]] Env: {{ $labels.namespace }} PVC: {{$labels.persistentvolumeclaim}}: usage is above 90% (current value is: {{ humanize $value}})'
          summary: '[[.CustomerName]] {{ $labels.namespace }}: Low data disk space'
      - alert: SolrLowDisk
        expr: ((1 - (kubelet_volume_stats_available_bytes{persistentvolumeclaim=~".*solr.*"}/kubelet_volume_stats_capacity_bytes)) * 100) > 65
        for: 2d
        labels:
          severity: s2
          env: '{{ $labels.namespace }}'
          customer: '[[.CustomerName]]'
          cluster: '[[.ClusterName]]'
          object: '{{ $labels.persistentvolumeclaim }}'
        annotations:
          description: 'Customer: [[.CustomerName]] Env: {{ $labels.namespace }} PVC: {{$labels.persistentvolumeclaim}}: usage is above 65% (current value is: {{ humanize $value}})'
          summary: '[[.CustomerName]] {{ $labels.namespace }}: Low data disk space'
      #- alert: VolumeFullInFiveDays
      #  expr: predict_linear(kubelet_volume_stats_available_bytes[6h], 5 * 24 * 3600) < 0
      #  for: 5m
      #  labels:
      #    severity: s3
      #    env: '{{ $labels.namespace }}'
      #    customer: '[[.CustomerName]]'
      #    cluster: '[[.ClusterName]]'
      #    object: '{{ $labels.persistentvolumeclaim }}'
      #    instance: '{{ $labels.instance }}'
      #    annotations:
      #    summary: "[[.CustomerName]] {{ $labels.namespace }}: Volume full in five days (instance {{ $labels.instance }})"
      #    description: "Customer: [[.CustomerName]] Env: {{ $labels.namespace }} PVC: {{$labels.persistentvolumeclaim}}: {{ $labels.namespace }}/{{ $labels.persistentvolumeclaim }} is expected to fill up within five days. Currently {{ $value | humanize }}% is available.\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
