apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-rules
data:
{{ (.Files.Glob "rules/shared/*.yaml").AsConfig | indent 2 }}
{{- if eq .Values.global.clusterType "prod" }}
{{ (.Files.Glob "rules/prod/*.yaml").AsConfig | indent 2 }}
{{ else }}
{{ (.Files.Glob "rules/non-prod/*.yaml").AsConfig | indent 2 }}
{{ end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-alertmanager
type: Opaque
data:
{{ (.Files.Glob "alertmanager-config.yaml").AsSecrets | indent 2 }}