apiVersion: v1
kind: Secret
metadata:
  name: gcr-repo-sa-secrets
  namespace: infra
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2djci5pbyI6eyJ1c2VybmFtZSI6Il9qc29uX2tleSIsInBhc3N3b3JkIjoie1xuICBcInR5cGVcIjogXCJzZXJ2aWNlX2FjY291bnRcIixcbiAgXCJwcm9qZWN0X2lkXCI6IFwibWFuYWdlZC1mdXNpb25cIixcbiAgXCJwcml2YXRlX2tleV9pZFwiOiBcImQ4ZTIxN2FhZTNjMGY2Y2VmZDcyNTMwNzlkZjBjNGI5ZTE4MjA2ZDZcIixcbiAgXCJwcml2YXRlX2tleVwiOiBcIi0tLS0tQkVHSU4gUFJJVkFURSBLRVktLS0tLVxcbk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRQ24yOUhGK1hJcUkvRUJcXG5CQVhOangxbTVxTlM4OHdNQU9rVk04dGgzVHpwL0lxUm1FRlFsekJvZUdwRTl0NGtPU3h2bmpQYWsyRG1iSG10XFxuTEduRUovNXZ4dUQydkt3YnJtV2tSeFJJZ3ZHMmpjL3cwNEQ2VmNidlhUcGFXUGYyRnNRbjB3V1dLeC9SK1lvRFxcblBhUDA4QlhBdU54OEZSQ00yd3hRS3VlVHNHTFBqb0pWVTkxMmpZcTQ4aWF0SCtjUmcyUmVmQVFXZ01OM0RkR2FcXG5ZZU0rbTB0emJhcFJlNGh1VXplby9DWVl0aEk0OGRheEx2NVpFRm5iUG9UUkhkS3JUTUdIRVg0dkdLR2dOMGhMXFxubWJLUG9JNDROMHh4QXRQSDRHNFdrTVFVTFJ0VnhpV2RPWmpaeVpYU09WeHUySEhGUDFxUkFTOGlodDZjeks3eVxcblBXbFFBa0pUQWdNQkFBRUNnZ0VBTmFTNlZWcHljYVVxei9oSkluZ3FIVWgzeVhyQUt0WGZwemIyT0VCTHh6czlcXG56V21xOWVaYlFnZTVibkMyYlQwWVJsTjRudEdhbGdqMG1iTW4yZGd1SitxVzJrTlJmVWN1bEdGaXlnbU8xWmhjXFxuYThvcjNkU3J6ck1zZ3RNTDYwazdScjdaZWpRdDV4eW9Ub0RVZE9LRkVTSUMxR1NtOVZ6TGdwTXpqcTgvNUxSUlxcbkJHSFc4dC94VzRiQkdaYmV0M01GZEVaU3Awckx1RzdibEdZTkxlVkxINGp5cGxnTmZWMW42Y1FkOHJ1OXp2T3pcXG5XWExlMFdLY0FqQ1Y5MDFvUExDZTlUcG5hcDlDV1pDV1lNVkxzd213bkJGQ0NyYTEzdS9wTmZqKytKMmtjWFVHXFxuQjU3SXVmR3d1RXlWSFVWelR6MkNTWUVPeWFqaEtpVXhMYkU3VjJqZ2dRS0JnUURuaElVb25ESTFndnF6Q1AzbFxcbkxPZmNyczhlRWMzSjRRSjIvUWYydzhSTUhqSnhIeXFzU1gxOFpMUDcrQVgzYmRYK0tSTVFPUnVibFlpdE0yVjRcXG4rbHFiWDF0UVlJdEhXcTI5b001cFZpbDFPWWZqSXJIVlJNdDJVZExiQWJpaTkvUExsdEtUQTNyTmhaN2R3cFZ2XFxuUGtEcTZ1NHpqZmxjTWV1QUF3dlhOTTRSZndLQmdRQzVtL2dIVTFSdnF3TnNOSStld282cENoUjNLT2tjVzZLc1xcbjZOSXQ4bjkzdnBmbGdHbW1mZUdZd2tibG1FSCtIQTVTekJkVXZ5SEJpYzljczhjNElCM1FiS0lUaWdWNEZmcGlcXG53U1JRS2NENmFtdkVmWW1CcTM1NXdBVnRwZlNhbWlNSHV6NjdOL2NKZjBuenNzZ3ZjMjFPSHVVZVFyWU9ObU92XFxuWTFVTnk4QlJMUUtCZ0dmK1VNbmpEM0tWK1FKK29YMVY1SGh1VlQ2T2hMK1B3TW10OHV2WEY4K1JLTnREUXFuTlxcbkFQN2xSU3VEUnpyVExYSlRCT3NlbTlZUkh5bWRrcEQ2ODhRaTJ5T0pta1pjNXZuc3g0cnRWd1grNTVrUk5vd3pcXG5zS2pmTERXUDJsM3B2cXJPZnB2bXpqeVBMc014Nm1uanJzbFc2ZFJpaTRYc0xucDc0OCt4T25jRkFvR0JBSUJyXFxuaVpDSDkwUEw3dkpPNjQvTXpTZm44WUVBclVrUm5keEV1aWRRUVNGNG5XQU5HUXc0ekg0RTdVaXRyL3RCTGlmYlxcblRjazA5UVlUYzRXUVhhWlhra2xDNEdEa2ZpUTRFS1dEUEx5Nkp1c2I5clJjcDJjd1lMR2NTaVV6VGFvcU8xSitcXG5HMGt0ejU2aWsyZ3BxcGdxSk5hSVNiNUdLZkJyY1UxSVRQRGVxSkdCQW9HQVRyTFJtUHh6WlJHM0c2eWZkVGx1XFxudmRMZHRLYndQcGQ0VWxNYjBRL2RPV09USHVmNGJ4TTNNaWFBTlp2Y2crSG9VV1lVRzZsVHFSVXVVczBCaWYxRFxcblpqSkZ6VUFEZW0zdVJtd3pHRzQxNHZSSkFHdW5zUmJScExia3NxSHVPY2dvKzhNQ0Zqeis0aXJNWXZWTkVCSEdcXG45S2tOTHFsb0tNZFNrS2VyVG0zaDBOaz1cXG4tLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tXFxuXCIsXG4gIFwiY2xpZW50X2VtYWlsXCI6IFwiZ2NyLXJlcG8tc2FAbWFuYWdlZC1mdXNpb24uaWFtLmdzZXJ2aWNlYWNjb3VudC5jb21cIixcbiAgXCJjbGllbnRfaWRcIjogXCIxMDc2ODA4NzY3NTk5ODQ2MTI2NzFcIixcbiAgXCJhdXRoX3VyaVwiOiBcImh0dHBzOi8vYWNjb3VudHMuZ29vZ2xlLmNvbS9vL29hdXRoMi9hdXRoXCIsXG4gIFwidG9rZW5fdXJpXCI6IFwiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW5cIixcbiAgXCJhdXRoX3Byb3ZpZGVyX3g1MDlfY2VydF91cmxcIjogXCJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9vYXV0aDIvdjEvY2VydHNcIixcbiAgXCJjbGllbnRfeDUwOV9jZXJ0X3VybFwiOiBcImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL3JvYm90L3YxL21ldGFkYXRhL3g1MDkvZ2NyLXJlcG8tc2ElNDBtYW5hZ2VkLWZ1c2lvbi5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbVwiXG59IiwiZW1haWwiOiJnY3ItcmVwby1zYUBtYW5hZ2VkLWZ1c2lvbi5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIsImF1dGgiOiJYMnB6YjI1ZmEyVjVPbnNLSUNBaWRIbHdaU0k2SUNKelpYSjJhV05sWDJGalkyOTFiblFpTEFvZ0lDSndjbTlxWldOMFgybGtJam9nSW0xaGJtRm5aV1F0Wm5WemFXOXVJaXdLSUNBaWNISnBkbUYwWlY5clpYbGZhV1FpT2lBaVpEaGxNakUzWVdGbE0yTXdaalpqWldaa056STFNekEzT1dSbU1HTTBZamxsTVRneU1EWmtOaUlzQ2lBZ0luQnlhWFpoZEdWZmEyVjVJam9nSWkwdExTMHRRa1ZIU1U0Z1VGSkpWa0ZVUlNCTFJWa3RMUzB0TFZ4dVRVbEpSWFpSU1VKQlJFRk9RbWRyY1docmFVYzVkekJDUVZGRlJrRkJVME5DUzJOM1oyZFRha0ZuUlVGQmIwbENRVkZEYmpJNVNFWXJXRWx4U1M5RlFseHVRa0ZZVG1wNE1XMDFjVTVUT0RoM1RVRlBhMVpOT0hSb00xUjZjQzlKY1ZKdFJVWlJiSHBDYjJWSGNFVTVkRFJyVDFONGRtNXFVR0ZyTWtSdFlraHRkRnh1VEVkdVJVb3ZOWFo0ZFVReWRrdDNZbkp0VjJ0U2VGSkpaM1pITW1wakwzY3dORVEyVm1OaWRsaFVjR0ZYVUdZeVJuTlJiakIzVjFkTGVDOVNLMWx2UkZ4dVVHRlFNRGhDV0VGMVRuZzRSbEpEVFRKM2VGRkxkV1ZVYzBkTVVHcHZTbFpWT1RFeWFsbHhORGhwWVhSSUsyTlNaekpTWldaQlVWZG5UVTR6UkdSSFlWeHVXV1ZOSzIwd2RIcGlZWEJTWlRSb2RWVjZaVzh2UTFsWmRHaEpORGhrWVhoTWRqVmFSVVp1WWxCdlZGSklaRXR5VkUxSFNFVllOSFpIUzBkblRqQm9URnh1YldKTFVHOUpORFJPTUhoNFFYUlFTRFJITkZkclRWRlZURkowVm5ocFYyUlBXbXBhZVZwWVUwOVdlSFV5U0VoR1VERnhVa0ZUT0dsb2REWmpla3MzZVZ4dVVGZHNVVUZyU2xSQlowMUNRVUZGUTJkblJVRk9ZVk0yVmxad2VXTmhWWEY2TDJoS1NXNW5jVWhWYURONVdISkJTM1JZWm5CNllqSlBSVUpNZUhwek9WeHVlbGR0Y1RsbFdtSlJaMlUxWW01RE1tSlVNRmxTYkU0MGJuUkhZV3huYWpCdFlrMXVNbVJuZFVvcmNWY3lhMDVTWmxWamRXeEhSbWw1WjIxUE1WcG9ZMXh1WVRodmNqTmtVM0o2Y2sxelozUk5URFl3YXpkU2NqZGFaV3BSZERWNGVXOVViMFJWWkU5TFJrVlRTVU14UjFOdE9WWjZUR2R3VFhwcWNUZ3ZOVXhTVWx4dVFrZElWemgwTDNoWE5HSkNSMXBpWlhRelRVWmtSVnBUY0RCeVRIVkhOMkpzUjFsT1RHVldURWcwYW5sd2JHZE9abFl4YmpaalVXUTRjblU1ZW5aUGVseHVWMWhNWlRCWFMyTkJha05XT1RBeGIxQk1RMlU1VkhCdVlYQTVRMWRhUTFkWlRWWk1jM2R0ZDI1Q1JrTkRjbUV4TTNVdmNFNW1haXNyU2pKclkxaFZSMXh1UWpVM1NYVm1SM2QxUlhsV1NGVldlbFI2TWtOVFdVVlBlV0ZxYUV0cFZYaE1Za1UzVmpKcVoyZFJTMEpuVVVSdWFFbFZiMjVFU1RGbmRuRjZRMUF6YkZ4dVRFOW1ZM0p6T0dWRll6TktORkZLTWk5UlpqSjNPRkpOU0dwS2VFaDVjWE5UV0RFNFdreFFOeXRCV0ROaVpGZ3JTMUpOVVU5U2RXSnNXV2wwVFRKV05GeHVLMnh4WWxneGRGRlpTWFJJVjNFeU9XOU5OWEJXYVd3eFQxbG1ha2x5U0ZaU1RYUXlWV1JNWWtGaWFXazVMMUJNYkhSTFZFRXpjazVvV2pka2QzQldkbHh1VUd0RWNUWjFOSHBxWm14alRXVjFRVUYzZGxoT1RUUlNabmRMUW1kUlF6VnRMMmRJVlRGU2RuRjNUbk5PU1N0bGQyODJjRU5vVWpOTFQydGpWelpMYzF4dU5rNUpkRGh1T1ROMmNHWnNaMGR0YldabFIxbDNhMkpzYlVWSUswaEJOVk42UW1SVmRubElRbWxqT1dOek9HTTBTVUl6VVdKTFNWUnBaMVkwUm1ad2FWeHVkMU5TVVV0alJEWmhiWFpGWmxsdFFuRXpOVFYzUVZaMGNHWlRZVzFwVFVoMWVqWTNUaTlqU21Zd2JucHpjMmQyWXpJeFQwaDFWV1ZSY2xsUFRtMVBkbHh1V1RGVlRuazRRbEpNVVV0Q1owZG1LMVZOYm1wRU0wdFdLMUZLSzI5WU1WWTFTR2gxVmxRMlQyaE1LMUIzVFcxME9IVjJXRVk0SzFKTFRuUkVVWEZ1VGx4dVFWQTNiRkpUZFVSU2VuSlVURmhLVkVKUGMyVnRPVmxTU0hsdFpHdHdSRFk0T0ZGcE1ubFBTbTFyV21NMWRtNXplRFJ5ZEZaM1dDczFOV3RTVG05M2VseHVjMHRxWmt4RVYxQXliRE53ZG5GeVQyWndkbTE2YW5sUVRITk5lRFp0Ym1weWMyeFhObVJTYVdrMFdITk1ibkEzTkRncmVFOXVZMFpCYjBkQ1FVbENjbHh1YVZwRFNEa3dVRXczZGtwUE5qUXZUWHBUWm00NFdVVkJjbFZyVW01a2VFVjFhV1JSVVZOR05HNVhRVTVIVVhjMGVrZzBSVGRWYVhSeUwzUkNUR2xtWWx4dVZHTnJNRGxSV1ZSak5GZFJXR0ZhV0d0cmJFTTBSMFJyWm1sUk5FVkxWMFJRVEhrMlNuVnpZamx5VW1Od01tTjNXVXhIWTFOcFZYcFVZVzl4VHpGS0sxeHVSekJyZEhvMU5tbHJNbWR3Y1hCbmNVcE9ZVWxUWWpWSFMyWkNjbU5WTVVsVVVFUmxjVXBIUWtGdlIwRlVja3hTYlZCNGVscFNSek5ITm5sbVpGUnNkVnh1ZG1STVpIUkxZbmRRY0dRMFZXeE5ZakJSTDJSUFYwOVVTSFZtTkdKNFRUTk5hV0ZCVGxwMlkyY3JTRzlWVjFsVlJ6WnNWSEZTVlhWVmN6QkNhV1l4UkZ4dVdtcEtSbnBWUVVSbGJUTjFVbTEzZWtkSE5ERTBkbEpLUVVkMWJuTlNZbEp3VEdKcmMzRklkVTlqWjI4ck9FMURSbXA2S3pScGNrMVpkbFpPUlVKSVIxeHVPVXRyVGt4eGJHOUxUV1JUYTB0bGNsUnRNMmd3VG1zOVhHNHRMUzB0TFVWT1JDQlFVa2xXUVZSRklFdEZXUzB0TFMwdFhHNGlMQW9nSUNKamJHbGxiblJmWlcxaGFXd2lPaUFpWjJOeUxYSmxjRzh0YzJGQWJXRnVZV2RsWkMxbWRYTnBiMjR1YVdGdExtZHpaWEoyYVdObFlXTmpiM1Z1ZEM1amIyMGlMQW9nSUNKamJHbGxiblJmYVdRaU9pQWlNVEEzTmpnd09EYzJOelU1T1RnME5qRXlOamN4SWl3S0lDQWlZWFYwYUY5MWNta2lPaUFpYUhSMGNITTZMeTloWTJOdmRXNTBjeTVuYjI5bmJHVXVZMjl0TDI4dmIyRjFkR2d5TDJGMWRHZ2lMQW9nSUNKMGIydGxibDkxY21raU9pQWlhSFIwY0hNNkx5OXZZWFYwYURJdVoyOXZaMnhsWVhCcGN5NWpiMjB2ZEc5clpXNGlMQW9nSUNKaGRYUm9YM0J5YjNacFpHVnlYM2cxTURsZlkyVnlkRjkxY213aU9pQWlhSFIwY0hNNkx5OTNkM2N1WjI5dloyeGxZWEJwY3k1amIyMHZiMkYxZEdneUwzWXhMMk5sY25Seklpd0tJQ0FpWTJ4cFpXNTBYM2cxTURsZlkyVnlkRjkxY213aU9pQWlhSFIwY0hNNkx5OTNkM2N1WjI5dloyeGxZWEJwY3k1amIyMHZjbTlpYjNRdmRqRXZiV1YwWVdSaGRHRXZlRFV3T1M5blkzSXRjbVZ3YnkxellTVTBNRzFoYm1GblpXUXRablZ6YVc5dUxtbGhiUzVuYzJWeWRtbGpaV0ZqWTI5MWJuUXVZMjl0SWdwOSJ9fX0=
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fusion-license
  namespace: infra
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: read-only
rules:
- apiGroups:
  - ""
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fusion-license
subjects:
- kind: ServiceAccount
  name: fusion-license
  namespace: infra
roleRef:
  kind: ClusterRole
  name: read-only
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: licensemonitor-configmap
  namespace: infra
data:
  NUMBER: "14"
  CLUSTER_NAME: {{ .Values.global.clusterName }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: licensemonitor
spec:
  jobTemplate:
    metadata:
      name: licensemonitor
    spec:
      template:
        spec:
          serviceAccountName: fusion-license
          containers:
          - image: gcr.io/managed-fusion/license-monitor2:latest
            name: licensemonitor
            envFrom:
              - configMapRef:
                   name: licensemonitor-configmap
          imagePullSecrets:
          - name: gcr-repo-sa-secrets
          nodeSelector:
            fusion_node_type: infra
          restartPolicy: OnFailure
  schedule: '0 8 * * *'
