prometheus-alerts:
  alertmanager:
    enabled: true
    configFromSecret: 'prometheus-alertmanager'
    configFileName: 'alertmanager-config.yaml'
    nodeSelector:
      fusion_node_type: infra
  kubeStateMetrics:
    enabled: false
  nodeExporter:
    enabled: false
  pushgateway:
    enabled: false
  server:
    nodeSelector:
      fusion_node_type: infra
    replicaCount: 1
    statefulSet:
      enabled: true
    persistentVolume:
      size: 300Gi
    retention: 2h
    global:
      scrape_interval: 15s
      scrape_timeout: 10s
    extraConfigmapMounts:
      - name: alertmanager-rules
        mountPath: /etc/config/alerts
        configMap: alertmanager-rules
        readOnly: true
  serverFiles:
    prometheus.yml:
      rule_files:
        - /etc/config/rules/*.yaml
        - /etc/config/alerts/*.yaml
  configmapReload:
    extraConfigmapMounts:
      - name: alertmanager-rules
        mountPath: /etc/config/alerts
        configMap: alertmanager-rules
        readOnly: true
    extraVolumeDirs:
      - /etc/alerts
  extraScrapeConfigs: |
    - job_name: ingress-nginx
      metrics_path: /metrics
      static_configs:
        - targets:
          - nginx-ingress-ingress-nginx-controller:80
          - nginx-ingress-ingress-nginx-controller-metrics:9913
          - nginx-ingress-ingress-nginx-controller-stats:18080 